name: Build
on:
  workflow_dispatch: {}
jobs:
  activation:
    name: Build for Windows 🔑
    runs-on: ubuntu-latest
    steps:
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Windows
